#!/usr/bin/env python3
"""Generate src/components/icons/libraryIcons.h — the favorites star.

The general icon pipeline (freeink-sdk gen_icons.py) rasterises SVGs through
rsvg and a luminance threshold. That is right for Lucide's stroked icons and
wrong for a tiny filled star: the threshold binarises antialiased edges one
pixel at a time, so a mathematically symmetric shape comes out lopsided at
16 px — which is exactly how it looked on the panel. This script rasterises
the star polygon itself, by pixel coverage with symmetric supersampling, so
the output is mirror-symmetric by construction and the tips stay attached.

Usage: python3 scripts/gen_star_icon.py   (writes the header in place)
"""

import math

OUT = 'src/components/icons/libraryIcons.h'
SIZES = (16, 24)
SAMPLES = 8          # supersampling grid per pixel axis
COVERAGE = 0.38      # ink threshold; below 0.5 so 1-px star tips survive
OUTER = 0.46         # outer radius, as a fraction of the box
INNER = 0.45         # inner radius, as a fraction of the outer (chunkier
                     # than the 0.382 pentagram ratio, for 1-bit legibility)


def star_polygon(px):
    R = px * OUTER
    r = R * INNER
    cx = px / 2.0
    # A star has more mass above its midline than below; offsetting the centre
    # down centres the BOUNDING BOX, which is what the eye centres.
    cy = px / 2.0 + 0.0955 * R
    pts = []
    for i in range(5):
        ao = math.radians(90 + i * 72)
        ai = math.radians(126 + i * 72)
        pts.append((cx + R * math.cos(ao), cy - R * math.sin(ao)))
        pts.append((cx + r * math.cos(ai), cy - r * math.sin(ai)))
    return pts


def point_in_polygon(x, y, poly):
    inside = False
    j = len(poly) - 1
    for i in range(len(poly)):
        xi, yi = poly[i]
        xj, yj = poly[j]
        if (yi > y) != (yj > y) and x < (xj - xi) * (y - yi) / (yj - yi) + xi:
            inside = not inside
        j = i
    return inside


def rasterize(px):
    poly = star_polygon(px)
    rows = []
    for y in range(px):
        row = []
        for x in range(px):
            hits = 0
            for sy in range(SAMPLES):
                for sx in range(SAMPLES):
                    if point_in_polygon(x + (sx + 0.5) / SAMPLES, y + (sy + 0.5) / SAMPLES, poly):
                        hits += 1
            row.append(hits / (SAMPLES * SAMPLES) >= COVERAGE)
        rows.append(row)
    # The geometry and the sample grid are both symmetric about the vertical
    # axis, so this is a no-op — asserted rather than trusted.
    for y in range(px):
        for x in range(px):
            assert rows[y][x] == rows[y][px - 1 - x], f'{px}px asymmetry at {x},{y}'
    return rows


def pack(rows, px):
    stride = (px + 7) // 8
    data = []
    for y in range(px):
        for xb in range(stride):
            byte = 0
            for b in range(8):
                x = xb * 8 + b
                if x >= px or not rows[y][x]:
                    byte |= 0x80 >> b  # 1 = blank, 0 = ink, as gen_icons packs
            data.append(byte)
    return data, stride


def main():
    parts = [
        '#pragma once\n\n#include "Icon.h"\n\n'
        '// Generated by scripts/gen_star_icon.py. Do not edit.\n'
        '// The favorites star, rasterised by coverage so it is mirror-symmetric\n'
        '// and centred by bounding box; see the script for why the SVG pipeline\n'
        '// is not used here.\n'
    ]
    for px in SIZES:
        rows = rasterize(px)
        data, stride = pack(rows, px)
        art = '\n'.join('// ' + ''.join('#' if c else '.' for c in row) for row in rows)
        hexes = ', '.join(f'0x{b:02X}' for b in data)
        parts.append(
            f'\n{art}\n'
            f'static const uint8_t icon_star_{px}_bits[] = {{{hexes}}};\n'
            f'static const freeink::Icon icon_star_{px} = {{{px}, {px}, {stride}, icon_star_{px}_bits}};\n'
        )
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(''.join(parts))
    print(f'wrote {OUT}')


if __name__ == '__main__':
    main()
